---

- name: Deploy the OpenCraft Instance Manager devstack
  hosts: all
  become: true
  vars:
    devstack: True
    www_user: ubuntu
    www_group: users
    www_data_home_dir: '/home/ubuntu'
    # The `opencraft` sources must be previously available.  The devstack tasks
    # will not clone it automatically.
    opencraft_root_dir: '{{ www_data_home_dir }}/src/ocim'
    opencraft_virtualenv_dir: '{{ www_data_home_dir }}/venvs/ocim'
  tasks:
    - import_role:
        name: ocim
        tasks_from: devstack
